ask_pupkin/ask_pupkin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ask_pupkin.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'asking.views.index'),
    url(r'^signup/$', 'asking.views.signup'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^answer/$', 'asking.views.answer'),
    url(r'^index/best/$', 'asking.views.index', {'sort': 'best'}),
    url(r'^ask/$', 'asking.views.ask'),
    url(r'^like/$', 'asking.views.like'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

ask_pupkin/asking/models.py
from django.db import models
from django.contrib.auth.models import User
from tagging.fields import TagField
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User)
    rating = models.IntegerField(default=0)
    avatar_url = models.ImageField(upload_to='users')

class Question(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=60)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    tags = TagField()

class Answer(models.Model):
    author = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_right = models.BooleanField(default=False) 

ask_pupkin/asking/views.py
from django.shortcuts import render_to_response, render, HttpResponseRedirect
from django.template import RequestContext
from models import Question, Answer, Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django import forms
from django.db import models
import json

# Create your views here.

class UserForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=60)    
    password = forms.CharField(widget=forms.PasswordInput())
    avatar = forms.ImageField()
     
    def clean_username(self):
        data = self.cleaned_data.get('username')
        try:
            User.objects.get(username=data)
        except (User.DoesNotExist):
           return data
        raise forms.ValidationError('This username is already taken. ')             
    
    def clean_email(self):
        data = self.cleaned_data.get('email')
        try:
            User.objects.get(email=data)
        except (User.DoesNotExist):
            return data
        raise forms.ValidationError('This email is already taken. ')             

class QuestionForm(forms.ModelForm):
   
    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        super(QuestionForm, self).__init__(*args, **kwargs)
    
    def save(self, commit=True):
        instance = super(QuestionForm, self).save(commit=False)
        instance.author = self.author
        if commit:
            instance.save()
        return instance    

    class Meta:
        model = Question
        fields = ['title', 'text', 'tags']

def index(request, sort='new'):
    page = request.GET.get('page')
    order = sort == 'best' and '-author__profile__rating' or '-date_added'
    question_list = Question.objects.order_by(order)

    paginator = Paginator(question_list, 3)

    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)
    
    isBest = sort == 'best' and True or False 
    return render_to_response('index.html', {'questions': questions, 'isBest': isBest}, context_instance=RequestContext(request))

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username, email, password)
            Profile.objects.create(user_id=user.id, avatar_url=request.FILES['avatar'])
            user = authenticate(username=username, password=password)
            login(request, user)
            redirect_to = request.GET.get('next')
            return HttpResponseRedirect(redirect_to)
    else:
        form = UserForm()
    
    return render(request, 'signup.html', {'form': form})

def answer(request):
    id_q = request.GET.get('id_q')
    question = Question.objects.get(id=id_q)
    
    if request.method == 'POST':
        if request.user.is_authenticated():
            author = request.user
            Answer.objects.create(author=author, question=question, text=request.POST['text'])
        else:
            return HttpResponseRedirect('/login/')
    
    answer_list = Answer.objects.filter(question_id=id_q)
    paginator = Paginator(answer_list, 3)

    page = request.GET.get('page')
    try:
        answers = paginator.page(page)
    except PageNotAnInteger:
        answers = paginator.page(1)
    except EmptyPage:
        answers = paginator.page(paginator.num_pages)
     
    return render_to_response('answer.html', {'answers': answers, 'question': question}, context_instance=RequestContext(request))

def ask(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            author = request.user
            form = QuestionForm(request.POST, author=author)
            if form.is_valid():
                form.save()
                redirect_to = request.GET.get('next')
                return HttpResponseRedirect(redirect_to) 
        else:
            form = QuestionForm()
        return render(request, 'ask.html', {'form': form})
    else:
        return HttpResponseRedirect('/login/')

def settings(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            request.user.username = form.cleaned_data['username']
            request.user.profile.email = form.cleaned_data['email']
            user = User.objects.create_user(username, email, password)
            Profile.objects.create(user_id=user.id, avatar_url=request.FILES['avatar'])
            user = authenticate(username=username, password=password)

def like(response):
    response_data = {}
    if request.user.is_authenticated():
        type = request.POST.get('type')
        id_user = request.POST.get('id')
        user = User.objects.get(id=id_user)
        if type == 'like':
            user.profile.rating = 10
            response_data['status'] = 'ok'
            response_data['new_rating'] = user.profile.rating 
        else:
            user.profile.raing = 13
            response_data['status'] = 'ok'
            response_data['new_rating'] = user.profile.rating
    else:
        response_data['status'] = 'error'
        responce_data['new_rating'] = 0;
    return HttpResponse(json.dumps(response_data), content_type="application/json")

ask_pupkin/templates/answer.html
{% extends "base.html" %}

{% block title %}Answer{% endblock %}

{% block content %}
<ul class="nav nav-tabs">
    <li><h3><a href="">{{ question.title }}</a></h3></li>
</ul>
<div class="question row-fluid">
    <div class="span3 imglike">
        <img src="{{ question.author.profile.avatar_url.url }}" class="img-rounded">
        <div>
            <p class="text-center"><a href="#">{{ question.author.username }}</a></p>
        </div>
        <div class="btn-group pull-left offset3">
            <button class="btn btn-small">-</button>
            <button class="btn btn-small" disabled>{{ question.author.profile.rating }}</button>
            <button class="btn btn-small">+</button>
        </div>
    </div>
    <div class="span8">
        <h4><a href="">{{ question.title }}</a></h4>
        <p>{{ question.text }}</p>
        <div>
            Tags: <a href="#">{{ question.tags }}</a>
            <div class="row-fluid">
                <p class="muted text-right">{{ question.date_added.ctime }}</p>
            </div>
        </div>
    </div>
</div>
<ul class="nav nav-tabs">
    <li><h3>Answers</h3></li>
</ul>

{% for answer in answers %}
<div class="question row-fluid">
    <div class="span3 imglike">
        <img src="{{ answer.author.profile.avatar_url.url }}" class="img-rounded">
        <div>
            <p class="text-center"><a href="#">{{ answer.author.username }}</a></p>
        </div>
        <div class="btn-group pull-left offset3">
            <button class="btn btn-small">-</button>
            <button class="btn btn-small" disabled>{{ answer.author.profile.rating }}</button>
            <button class="btn btn-small">+</button>
        </div>
    </div>
    <div class="span8">
        <br><p>{{ answer.text }}</p>
        <div class="row-fluid">
            <p class="muted text-right">{{ answer.date_added.ctime }}</p>
        </div>
    </div>
</div>
{% endfor %}

<div class="pagination">
    <ul>
        {% if answers.has_previous %}
        <li><a href="?id_q={{ question.id }}&page={{ answers.previous_page_number }}">Prev</a></li>
        {% else %} 
        <li class="disabled"><a href="#">Prev</a></li>
        {% endif %}
        {% if answers.has_next %}
        <li><a href="?id_q={{ question.id }}&page={{ answers.next_page_number }}">Next</a></li>
        {% else %}
        <li class="disabled"><a href="#">Next</a></li>
        {% endif %}         
    </ul>
</div>

<form class="form-horizontal" method="post" action="">
    {% csrf_token %}
    <fieldset>
        <legend>Your answer</legend>
        <div class="control-group">
            <textarea rows="10" cols="10" name="text"></textarea>
        </div>
        <div class="form-action">
            <div class="control-group">
                <button type="submit" class="btn btn-primary">Answer</button>
            </div>
        </div>
    </fieldset>
</form>

{% endblock %}

ask_pupkin/templates/ask.html
{% extends "base.html" %}

{% block title %}Ask{% endblock %}

{% block content %}
<form class="form-horizontal" enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    <fieldset>
        <legend>Question</legend>
        {% for field in form %}
            <div class="control-group">
                <label class="control-label" for="inputLogin">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
        {% endfor %}
        <div class="form-action">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Ask!</button>
            </div>
        </div>
   </fieldset>
</form>
{% endblock %}

ask_pupkin/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}/AskPupkin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" media="screen" type="text/css">
    <style>
        .question {
            border: solid 1px lightgray;
            margin-bottom: 30px;
            padding-bottom: 10px;
        }
        .imglike {
            padding-top: 10px;
            padding-left: 10px;
        }
        .warning {
            margin: 0 0;
            margin-top: 5px;
        }
    </style>
  </head>
  <body>

	<div class="navbar">
 		<div class="navbar-inner">
    		<a class="brand" href="/">AskPupkin</a>
			<form class="navbar-search form-search">
                <div class="input-append">
  				    <input type="text" class="search-query" placeholder="Search">
                    <button type="submit" class="btn">Find!</button>
                </div>
			</form>
            {% include "userblock.html" %}
            <a href="{% url 'asking.views.ask' %}?next={{ request.path }}" class="btn pull-right">Ask!</a>
  		</div>
	</div>    
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span8">
				{% block content %}{% endblock %}
			</div>
			<div class="span3 offset1">
				<h3>Popular Tags</h3>
					<a href="#">best</a>
					<a href="#">Lucky</a>
					<a href="#">lol</a>
					<a href="#">Funny</a>
				<h3>Best Members</h3>
					<ul>
						<li><a href="#">Lesha</a></li>
                        <li><a href="#">Saha</a></li>
                        <li><a href="#">Dasha</a></li>
                        <li><a href="#">Pashqa</a></li>
                        <li><a href="#">Natali</a></li>
					</ul>
			</div>
		</div>
	</div>

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <script src="{% static "js/askjs.js" %}"></script>
  </body>
</html>

ask_pupkin/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}
{% if not isBest %}
<ul class="nav nav-tabs">
    <li class="active"><a href="/">New</a></li>
    <li><a href="index/best/">Best</a></li>
</ul>
{% else %}
<ul class="nav nav-tabs">
    <li><a href="/">New</a></li>
    <li class="active"><a href="">Best</a></li>
</ul>
{% endif %}
{% for question in questions %}
<div class="question row-fluid">
    <div class="span3 imglike">
        <img src="{{ question.author.profile.avatar_url.url }}" class="img-rounded">
        <div>
            <p class="text-center"><a href="#">{{ question.author.username }}</a></p>
        </div>
        <div class="btn-group pull-left offset3">
            <button class="btn btn-small js_dislike" data-id="{{ question.author.id }}">-</button>
            <button class="btn btn-small js_cnt" disabled>{{ question.author.profile.rating }}</button>
            <button class="btn btn-small js_like" data-id="{{ question.author.id }}">+</button>
        </div>
    </div>
    <div class="span8">
        <h4><a href="../../answer/?id_q={{ question.id }}">{{ question.title }}</a></h4>
        <p>{{ question.text }}</p>
        <div>
            <a href="../../answer/?id_q={{ question.id }}">answer <span class="badge">{{ question.answer_set.count }}</span></a>
            Tags: <a href="">{{ question.tags }}</a>
            <div class="row-fluid">
                <p class="muted text-right">{{ question.date_added.ctime }}</p>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<div class="pagination">
    <ul>
        {% if questions.has_previous %}
            <li><a href="?page={{ questions.previous_page_number }}">Prev</a></li>
         {% else %} 
            <li class="disabled"><a href="#">Prev</a></li>
        {% endif %}
        {% if questions.has_next %}
            <li><a href="?page={{ questions.next_page_number }}">Next</a></li>
        {% else %}
            <li class="disabled"><a href="#">Next</a></li>
        {% endif %}         
    </ul>
</div>
{% endblock %}

ask_pupkin/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<form class="form-horizontal" method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
    <fieldset>
        <legend>Log In</legend>

        {% if form.non_field_errors %}
            <div class="control-group alert">{{ form.non_field_errors }}</div>
        {% endif %}
        <div class="control-group">
            <label class="control-label" for="id_username">Login</label>
            <div class="controls">
                <input type="text" id="id_username" name="username" placeholder="Enter you login here">
            </div>
        </div>
        {% if form.username.errors %}
            <div class="controls alert">{{ form.username.errors }}</div>
        {% endif %}
        <div class="control-group">
            <label class="control-label" for="id_password">Password</label>
            <div class="controls">
                <input type="password" id="id_password" name="password" placeholder="Password">
            </div>
        </div>
        {% if form.password.errors %}
            <div class="controls alert">{{ form.password.errors }}</div>
        {% endif %}
        <div class="control-group">
            <div class="controls">
                <input type="submit" value="Log In!" class="btn"/>
                <input type="hidden" name="next" value="{{ '/' }}" />
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <a href="../signup/">Create new account</a>
            </div>
        </div>
    </fieldset>
</form>
{% endblock %}

ask_pupkin/templates/profile.html
{% extends "base.html" %}

{% block title %}Settings{% endblock %}
                                                                                                    
{% block content %}
<form class="form-horizontal" enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    <fieldset>
        <legend>Settings</legend>
        {% if form.non_field_errors %}
            <div class="control-group alert">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
            <div class="control-group">
                <label class="control-label" for="inputLogin">{{ field.label }}</label>
                <div class="controls"><input type=""></div>
            </div>
            {% if field.errors %}
                <div class="controls alert">{{ field.errors }}</div>
            {% endif %}
        {% endfor %}
        <div class="form-action">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Change</button>
            </div>
        </div>
    </fieldset>
</form>
{% endblock %}

ask_pupkin/templates/signup.html
{% extends "base.html" %}

{% block title %}Signup{% endblock %}
                                                                                                    
{% block content %}
<form class="form-horizontal" enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    <fieldset>
        <legend>Registration</legend>
        {% if form.non_field_errors %}
            <div class="control-group alert">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
            <div class="control-group">
                <label class="control-label" for="inputLogin">{{ field.label }}</label>
                <div class="controls">{{ field }}</div>
            </div>
            {% if field.errors %}
                <div class="controls alert">{{ field.errors }}</div>
            {% endif %}
        {% endfor %}
        <div class="form-action">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Registrate</button>
            </div>
        </div>
    </fieldset>
</form>
{% endblock %}

ask_pupkin/templates/userblock.html
{% if user.is_authenticated %}
    <ul class="nav pull-right">
        <div class="span1">
            <img src="" class="img-rounded">
        </div>
        <div class="span2">
            {{ user.username }}<br>
            <a href="#">Settings</a> <a href="{% url 'django.contrib.auth.views.logout' %}?next={{ request.path }}">Log out</a>
        </div>
    </ul>  
{% else %}
    <ul class="nav pull-right">
        <li><a href="{% url 'django.contrib.auth.views.login' %}?next={{ request.path }}">Log in</a></li>
        <li><a href="{% url 'asking.views.signup' %}?next={{ request.path }}">Register</a></li>
    </ul>
{% endif %}